# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches: 
    include:
      - master
      - refs/tags/v*

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  
steps:
  - script: dotnet restore
    displayName: 'dotnet restore'
  
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'

  - script: dotnet test MailerTests/
    displayName: 'dotnet test'
  
  - task: Docker@1
    displayName: Container registry login
    inputs:
      containerregistrytype: Container Registry
      dockerRegistryEndpoint: DockerHub
      command: login
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))  
  
  - script: docker build -t roymoran/mailer -f ci/Dockerfile .
    displayName: 'build docker image'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))  
    
  - script: docker push roymoran/mailer
    displayName: 'push docker image'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))  
  
  