# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches: 
    include:
      - master
      - refs/tags/v*

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  busConnectionString: $(ServiceBusConnectionString)
  queueName: $(ServiceBusQueueName)
  
steps:
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      contents: '**/*'
      targetFolder: $(Build.ArtifactStagingDirectory)
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'),contains(variables['Build.SourceBranch'], 'refs/tags/v')))
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish src to: $(Build.ArtifactStagingDirectory)'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
      artifactName: 'deploy' 
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'),contains(variables['Build.SourceBranch'], 'refs/tags/v')))
  
  - script: dotnet restore
    displayName: 'dotnet restore'
  
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'

  - script: dotnet test MailerTests/
    displayName: 'dotnet test'
  
  - task: Docker@1
    displayName: Container registry login
    inputs:
      containerregistrytype: Container Registry
      dockerRegistryEndpoint: DockerHub
      command: login
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))  
  
  - script: docker build --build-arg SMTP_SERVER="$(smptServerAddress)" --build-arg SMTP_PORT="$(mailPort)" --build-arg SMTP_USERNAME="$(mailUsername)" --build-arg SMTP_PASSWORD="$(mailPassword)" --build-arg SERVICE_BUS_CONNECTION_STRING="$(busConnectionString)" --build-arg SERVICE_BUS_QUEUE_NAME="$(queueName)" -t roymoran/mailer:build -f ci/Dockerfile .
    displayName: 'build docker image'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))  
    
  - script: docker push roymoran/mailer:build
    displayName: 'push docker image'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))  
  
  